repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: ['--unsafe']
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.9
        args: [--config=pyproject.toml]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    -   id: seed-isort-config
        args: [--exclude=templates/]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        types: [file, python]
        args: [--settings-path=pyproject.toml]
